# Generated by Django 5.0.4 on 2024-04-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('DR_NAME', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('DR_AREA', models.CharField(blank=True, max_length=5, null=True)),
                ('DR_STAT', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('D_FTND', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('D_CLSD', models.BooleanField(default=False)),
                ('D_BAGSN', models.CharField(blank=True, max_length=30, null=True)),
                ('D_ZONE', models.CharField(blank=True, max_length=5, null=True)),
                ('D_SENT', models.BooleanField(default=False)),
                ('D_DRVR1', models.ForeignKey(blank=True, db_column='DR_NAME', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dep_main_related', to='Board.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('A_FTNA', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('A_CLSD', models.BooleanField(default=False)),
                ('A_DRVR1', models.ForeignKey(blank=True, db_column='DR_NAME', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arr_main_related', to='Board.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Hidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_HDDN', models.BooleanField(default=False)),
                ('H_FTND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.departure')),
                ('H_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('R_STAND', models.CharField(blank=True, max_length=20, null=True)),
                ('R_ACREG', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('R_APTA', models.CharField(blank=True, max_length=20, null=True)),
                ('R_STA', models.TimeField(blank=True, null=True)),
                ('R_ETA', models.TimeField(blank=True, null=True)),
                ('R_NA', models.CharField(blank=True, max_length=100, null=True)),
                ('R_RMPAG', models.CharField(blank=True, max_length=20, null=True)),
                ('R_APTD', models.CharField(blank=True, max_length=20, null=True)),
                ('R_STD', models.TimeField(blank=True, null=True)),
                ('R_ETD', models.TimeField(blank=True, null=True)),
                ('R_SLT', models.TimeField(blank=True, null=True)),
                ('R_ND', models.CharField(blank=True, max_length=100, null=True)),
                ('R_AOG', models.BooleanField(default=False)),
                ('R_OOT', models.TimeField(blank=True, null=True)),
                ('R_IOT', models.TimeField(blank=True, null=True)),
                ('R_FTNA', models.ForeignKey(blank=True, db_column='A_FTNA', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_related', to='Board.arrival')),
                ('R_FTND', models.ForeignKey(blank=True, db_column='D_FTND', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_related', to='Board.departure')),
            ],
        ),
    ]
